[tool.poetry]
name = "docker-test"
version = "0.1.0"
description = "Teste"
authors = ["pmirandaf <pablo.miranda.oliveira@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
